<?php
require_once($_SERVER['DOCUMENT_ROOT']."/Server-Side/promote.php");
$user = new adventurer();
$user->killCache();
$returnObj = ["signedIn" => $user->signedIn, "emailConfirmed" => $user->emailConfirmed, "userInfo" => []]; //or have this obj generated by promote

if (isset($_POST) AND count($_POST) > 0){
  if (isset($_POST['uname']) AND isset($_POST['psw'])){
    $subUname = str_replace("'", "", $_POST['uname']);
    $subPsw = $_POST['psw'];

    //echo $return; exit;
    if ($user->signIn($subUname, $subPsw)) {
      $returnObj = ["signedIn" => $user->signedIn, "emailConfirmed" => $user->emailConfirmed];
    }
  }
}

header('Content-Type: application/json');
echo json_encode($returnObj);


?>
